# Project: trabajo 2
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o submenu.o estudiante.o libros.o prestamos.o
LINKOBJ  = main.o submenu.o estudiante.o libros.o prestamos.o
LIBS     = -L"C:/Users/cristopher/Downloads/Dev-Cpp/MinGW64/lib" -L"C:/Users/cristopher/Downloads/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/cristopher/Downloads/Dev-Cpp/MinGW64/include" -I"C:/Users/cristopher/Downloads/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/cristopher/Downloads/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/cristopher/Downloads/Dev-Cpp/MinGW64/include" -I"C:/Users/cristopher/Downloads/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/cristopher/Downloads/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/cristopher/Downloads/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = "trabajo 2.exe"
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

submenu.o: submenu.c
	$(CC) -c submenu.c -o submenu.o $(CFLAGS)

estudiante.o: estudiante.c
	$(CC) -c estudiante.c -o estudiante.o $(CFLAGS)

libros.o: libros.c
	$(CC) -c libros.c -o libros.o $(CFLAGS)

prestamos.o: prestamos.c
	$(CC) -c prestamos.c -o prestamos.o $(CFLAGS)
